In [2]:
import torch 
import numpy as np



In [5]:
x=torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [6]:
x[1,1]

tensor(3)

In [7]:
type(x[1,1])

torch.Tensor

In [9]:
x[:,1] #evey row, col1 

tensor([1, 3, 5])

In [11]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

view() and reshape() do essential the same thing by returning a reshaped tensor wihout changing the original tensor in place 
view can also infer the correct size


In [17]:
x=torch.arange(0,10)
z= x.view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
x[0] = 100
print('x = ',x)
print('z = ', z)

x =  tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])
z =  tensor([[100,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


In [27]:
x=torch.arange(0,10)
#infer what the 2nd dimension 
x.view(2,-1)
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])
a+b

tensor([5., 7., 9.])

In [34]:
torch.add(a,b)

tensor([5., 7., 9.])

In [35]:
a.add_(b) # same as a= a+b

tensor([5., 7., 9.])

In [36]:
a

tensor([5., 7., 9.])

## Dot products
A <a href='https://en.wikipedia.org/wiki/Dot_product'>dot product</a> is the sum of the products of the corresponding entries of two 1D tensors. If the tensors are both vectors, the dot product is given as:<br>

$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d & e & f \end{bmatrix} = ad + be + cf$

If the tensors include a column vector, then the dot product is the sum of the result of the multiplied matrices. For example:<br>
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d \\ e \\ f \end{bmatrix} = ad + be + cf$<br><br>
Dot products can be expressed as <a href='https://pytorch.org/docs/stable/torch.html#torch.dot'><strong><tt>torch.dot(a,b)</tt></strong></a> or `a.dot(b)` or `b.dot(a)`

In [43]:
a =torch.tensor([1.,2.,3.])
b= torch.tensor([4.,5.,6.])
a*b

tensor([ 4., 10., 18.])

In [44]:
a.mul(b) # a*b

tensor([ 4., 10., 18.])

tensor([1., 2., 3.])

In [46]:
a.dot(b) 

tensor(32.)

## Matrix multiplication
2D <a href='https://en.wikipedia.org/wiki/Matrix_multiplication'>Matrix multiplication</a> is possible when the number of columns in tensor <strong><tt>A</tt></strong> matches the number of rows in tensor <strong><tt>B</tt></strong>. In this case, the product of tensor <strong><tt>A</tt></strong> with size $(x,y)$ and tensor <strong><tt>B</tt></strong> with size $(y,z)$ results in a tensor of size $(x,z)$
<div>
<div align="left"><img src='../Images/Matrix_multiplication_diagram.png' align="left"><br><br>

$\begin{bmatrix} a & b & c \\
d & e & f \end{bmatrix} \;\times\; \begin{bmatrix} m & n \\ p & q \\ r & s \end{bmatrix} = \begin{bmatrix} (am+bp+cr) & (an+bq+cs) \\
(dm+ep+fr) & (dn+eq+fs) \end{bmatrix}$</div></div>

<div style="clear:both">Image source: <a href='https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram_2.svg'>https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram_2.svg</a></div>

Matrix multiplication can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.mm'><strong><tt>torch.mm(a,b)</tt></strong></a> or `a.mm(b)` or `a @ b`

In [48]:
a = torch.tensor([[0,2,4],[1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [50]:
b = torch.tensor([[6,7],[8,9],[10,11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [51]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [52]:
a@b

tensor([[56, 62],
        [80, 89]])

## L2 or Euclidian Norm
See <a href='https://pytorch.org/docs/stable/torch.html#torch.norm'><strong><tt>torch.norm()</tt></strong></a>

The <a href='https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm'>Euclidian Norm</a> gives the vector norm of $x$ where $x=(x_1,x_2,...,x_n)$.<br>
It is calculated as<br>

${\displaystyle \left\|{\boldsymbol {x}}\right\|_{2}:={\sqrt {x_{1}^{2}+\cdots +x_{n}^{2}}}}$


When applied to a matrix, <tt>torch.norm()</tt> returns the <a href='https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm'>Frobenius norm</a> by default.

In [57]:
x = torch.tensor([2.,3.,4.,5.])
x.norm()

tensor(7.3485)

In [59]:
x.numel() #number element

4

In [60]:
len(x)

4

In [61]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [62]:
len(a)

2

In [63]:
a.numel()

6