Pytorch tensors:
    - Basics
    - Creating Tensors
    - Operations
    - Exercise
A Tensor is often thought of as a generalized matrix  (1D, 2D, 3D, 4D)


In [ ]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [6]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.dtype)
type(a)

[1 2 3 4 5 6]
int32


numpy.ndarray

In [9]:
x = torch.from_numpy(a)
x

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [10]:
type(x)


torch.Tensor

In [11]:
torch.as_tensor(a)


tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [13]:
a_2d = np.arange(0.0,12.0)
a_2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [16]:
a_2d = a_2d.reshape(4,3)
a_2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [15]:
torch.from_numpy(a_2d)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [17]:
a

array([1, 2, 3, 4, 5, 6])

In [18]:
x

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [19]:
a[0] =99

In [20]:
a

array([99,  2,  3,  4,  5,  6])

In [21]:
x

tensor([99,  2,  3,  4,  5,  6], dtype=torch.int32)

In [23]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_tensor = torch.tensor(my_arr)
my_tensor


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [26]:
my_other_tensor = torch.from_numpy(my_arr) 
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

khác nhau: khi thay đổi giá trị trong my_arr, sử dụng:

    - from_numpy() thì giá trị của tensor cũng bị thay đổi
    - tensor() thì giá trị không đổi

In [28]:
my_arr[0]=100

In [29]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [30]:
my_other_tensor

tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [34]:
new_arr = np.array([1,2,3])
new_arr.dtype

dtype('int32')

In [35]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [36]:
torch.Tensor(new_arr) # Tensor  <=> FloatTensor 

tensor([1., 2., 3.])

In [37]:
torch.FloatTensor(new_arr)

tensor([1., 2., 3.])

In [39]:
torch.empty(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [40]:
torch.zeros(4,3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [42]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [44]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [45]:
torch.tensor([1,2,3])


tensor([1, 2, 3])

In [47]:
my_tensor = torch.tensor([1,2,3])
my_tensor

tensor([1, 2, 3])

In [48]:
my_tensor.dtype

torch.int64

In [51]:
my_tensor = my_tensor.type(torch.int32) #convert from int64 to int32
my_tensor.dtype

torch.int32

In [52]:
torch.rand(4,3) # random (0,1)

tensor([[0.8952, 0.8005, 0.6199],
        [0.3820, 0.4168, 0.2190],
        [0.6570, 0.0617, 0.9391],
        [0.8635, 0.6102, 0.3998]])

In [53]:
torch.randn(4,3) #n: normalize 

tensor([[ 1.0990, -0.5524,  0.0174],
        [-0.6431, -0.1061,  0.6148],
        [-0.9635,  0.3303,  0.2863],
        [-0.0617, -1.3144,  1.0002]])

In [56]:
torch.randint(low=0, high=11, size = (5,5))

tensor([[ 5,  7,  3,  5,  4],
        [ 0,  7, 10,  7,  5],
        [ 1,  2,  2,  7,  0],
        [ 0,  8,  0,  9, 10],
        [10,  9,  1,  1,  9]])

In [58]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [59]:
x.shape

torch.Size([2, 5])

In [61]:
torch.rand_like(x)

tensor([[0.4560, 0.7745, 0.7242, 0.3707, 0.7023],
        [0.0440, 0.5614, 0.4095, 0.1320, 0.5324]])

In [62]:

torch.randn_like(x)

tensor([[ 0.7854, -0.1511,  1.8587,  0.0735, -0.5215],
        [-0.2238,  0.5800,  0.5719, -2.4994,  0.9117]])

In [64]:
torch.randint_like(x, low=0, high=10)

tensor([[2., 6., 5., 3., 3.],
        [0., 9., 1., 2., 2.]])

In [80]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [81]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])