In [1]:
#1 import numpy as np
import numpy as np

In [3]:
# create an array of 10 zeros 
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#create an array of 10 ones
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
#create an array of 10 fives
b*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
#create an array of the integers from 10 to 50 
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
#create an array of all the even integers from 10 to 50 
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
#create a 3x3 matrix with values ranging from 0 to 8
m = np.arange(0,9)
m.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
#generate a random number between 0 and 1
np.random.rand(1)

array([0.26503772])

In [14]:
#generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([ 1.16786826, -1.10450226, -1.0807222 ,  0.95289968, -1.26083508,
       -0.06126887,  0.92996171,  1.11028939, -0.72317337, -1.02696061,
        0.17968055,  0.23808227, -1.16698447, -1.88510507, -0.25543896,
        0.15295047, -0.20225312,  0.70993704, -0.28164852, -1.27329883,
       -0.30239167,  0.87409016, -0.18539962,  2.38180942, -1.04797729])