In [1]:
import numpy as np

In [9]:
#tạo list a 
a = [1,2,3]
type(a) #kiểm tra kiểu 

list

In [11]:
np.array(a) #đưa về dạng mảng 

array([1, 2, 3])

In [12]:
type(a)

list

In [14]:
nest_list = [[1,2,3], [4,5,6], [7,8,9]] 
nest_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
matrix = np.array(nest_list) #2-dimensional matrix
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
matrix.shape

(3, 3)

In [20]:
np.arange(0,10,2) #(start,end,steps)

array([0, 2, 4, 6, 8])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
# type(0.)

float

In [23]:
np.zeros((4,10)) #truyền vào tuple

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [26]:
np.ones(4) *10

array([10., 10., 10., 10.])

In [27]:
[1,1,1,1] * 100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [28]:
[1,1,1,1 ] + 10

TypeError: can only concatenate list (not "int") to list

In [32]:
np.linspace(0,10,2) #(start, end, how many numbers we want)

array([ 0., 10.])

In [33]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [34]:
np.eye(5) #ma trận đường chéo =1 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(1) 

array([0.07535546])

In [37]:
np.random.rand(2,3)

array([[0.75312936, 0.7541281 , 0.87643845],
       [0.52934952, 0.93766558, 0.37787773]])

In [38]:
# standard normal distribution, mean = 0, standard deviation (độ lệch chuẩn)= 1
np.random.randn(2,2)

array([[ 0.77792702,  0.01429265],
       [-0.16262163,  2.32037675]])

In [40]:
# np.random.normal()
np.random.randint(1,100,10)



array([98, 49, 91,  5, 19, 97, 83, 56, 24, 51])

In [52]:
"""
seed(): dùng để đối chiếu kết quả tỏng các lần chạy khác nhau
"""
np.random.seed (42) # khởi tạo các bộ sinh số ngẫu nhiên 

np.random.rand(4) #kết quả chạy luôn là các số giống nhau trong mỗi lần thử 

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [53]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [54]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [55]:
np.random.rand(4)

array([0.83244264, 0.21233911, 0.18182497, 0.18340451])

In [59]:
b =np.random.randint(0,50,10)
b

array([43,  7, 46, 34, 13, 16, 35, 49, 39,  3])

In [61]:
b.max()
b.min() #trả value

3

In [63]:
b.argmax() #trả index

7

In [66]:
b.dtype

dtype('int32')