In [1]:
import numpy as np

In [30]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a[0] 

0

In [9]:
a[1:5] #1 up to 5

array([1, 2, 3, 4])

In [11]:
a[0:5]
a[:5]

array([0, 1, 2, 3, 4])

In [12]:
a[5:]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
a + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [18]:
new_a=a/2
new_a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [20]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
slice_of_array = a[0:6]
slice_of_array 

array([0, 1, 2, 3, 4, 5])

In [25]:
slice_of_array[:]=99 #gán giá trị của các phần tử = 99 >> thay đổi giá trị trong a 

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
a_copy = a.copy() 
a_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
a_copy[:]=100

In [35]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
print(arr_2d.shape)
print(arr_2d[1][1])  
print(arr_2d[1,1])

(3, 3)
5
5


In [43]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [44]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
a>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [49]:
bool = a>4
bool 
a[bool]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
a[a==2]

array([2])