In [1]:
import numpy as np

In [3]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [5]:
a/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [6]:
a**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [8]:
(a+2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11, 0.12])

In [9]:
a+a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
1/a  #1/0

C:\Users\thomtt10\Anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [13]:
a/a #0/0

C:\Users\thomtt10\Anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [15]:
np.log(a)

C:\Users\thomtt10\Anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [16]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [17]:
a.sum()

55

In [18]:
a.mean()

5.0

In [19]:
a.max()

10

In [26]:
a_2d =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a_2d
a_2d.shape
a_2d.sum()

78

In [31]:
# across the rows
a_2d.sum(axis=0) #sum of value in columns


array([15, 18, 21, 24])

In [32]:
a_2d.sum(axis=1)

array([10, 26, 42])